# Introduction

<img src="images/software_overview.png" alt="drawing" width="800"/>

<img src="images/install_python.png" alt="drawing" width="900"/>

If you prefer a Matlab like experience, use the **Spyder IDE**, it comes with Anaconda.

If you like to make a notebook with your code, use **JupyterLabs**

<img src="images/data_layout.png" alt="drawing" width="1000"/>

<img src="images/tall_vs_wide.png" alt="drawing" width="1000"/>

## Better Example of Tall Format Data
<img src="images/example_tall.png" alt="drawing" width="750"/>

In [1]:
import pandas as pd
wide = pd.read_csv('data/dist_v_time.csv')
tall = pd.read_csv('data/dist_v_time_tall.csv')
display(wide)
display(tall)

    Time         S1         S2          S3         S4
0      0   0.000000   0.000000    0.000000   0.000000
1     10  17.133795  12.195851   21.187260   9.107360
2     20  24.027567  17.456237   33.473938   5.187678
3     30  29.128881  21.598526   39.134777   8.927878
4     40  34.210095  25.909595   41.520706  17.266036
5     50  29.891332  26.233662   46.280139  20.506097
6     60  37.039804  30.028531   55.344932   8.365644
7     70  43.734501  32.992294   61.159848  15.059880
8     80  47.242018  34.823032   66.858433  16.994117
9     90  54.678656  36.429439   65.411713  20.965901
10   100  54.818182  42.200000   67.150000  22.200000
11   110  58.828642  41.078347   70.165312  18.039512
12   120  46.705796  42.795389   80.131810  28.262484
13   130  57.423381  45.112941   75.251578  18.812895
14   140  59.268363  44.094515   83.239243  30.881936
15   150  53.554753  52.500730   81.200585  22.167882
16   160  64.855440  47.054692   88.037810  14.546477
17   170  57.843105  49.111325   92.311906  32.856780
18   180  74.278113  57.824718   89.889933  13.416408
19   190  69.922720  58.490314   92.008525  24.122085
20   200  73.924800  51.948778   97.651446  26.304372
21   210  60.336823  55.743496  102.019292  39.996200
22   220  78.881384  61.010593  105.606667  34.707809
23   230  88.237096  60.814661   99.108182  42.009130
24   240  67.882835  62.845610  103.021357  20.449352
25   250  66.120351  61.084663  116.688046  22.294058
26   260  85.606519  60.144443  107.873009  30.636579
27   270  88.432297  63.754906  119.211815  22.511397
28   280  75.299402  71.785430  113.283768  49.362942
29   290  96.912690  62.497848  118.779970  20.946145
30   300  90.066642  65.356050  113.535930  28.578838

     Time Sample  Distance, mm2
0       0     S1       0.000000
1      10     S1      17.133795
2      20     S1      24.027567
3      30     S1      29.128881
4      40     S1      34.210095
..    ...    ...            ...
119   260     S4      30.636579
120   270     S4      22.511397
121   280     S4      49.362942
122   290     S4      20.946145
123   300     S4      28.578838

[124 rows x 3 columns]

## Elements of a Figure in Python Matplotlib

<img src="images/sphx_glr_anatomy_001.png" alt="drawing" width="580"/>

From https://matplotlib.org/3.1.1/gallery/showcase/anatomy.html

## Useful References

(Source: http://ehmatthes.github.io/pcc/cheatsheets/README.html)

**Python and Matplotlib**

Python Beginner Cheat Sheet - https://github.com/ehmatthes/pcc/releases/download/v1.0.0/beginners_python_cheat_sheet_pcc.pdf)

Matplotlib (Python plotting) Cheat Sheet - https://github.com/ehmatthes/pcc/releases/download/v1.0.0/beginners_python_cheat_sheet_pcc_matplotlib.pdf


**Statistics**

Graphpad overview of statistics and errors: https://www.graphpad.com/guides/prism/latest/statistics/confidence_intervals.htm